name: Rollback Deployment

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Enter tag to rollback (example: v1.0)'
        required: true

jobs:
  rollback:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Fetch all tags
      run: git fetch --all --tags

    - name: Checkout Selected Tag
      run: git checkout ${{ github.event.inputs.tag }}

    - name: Remove old production folder
      run: rm -rf production

    - name: Create production folder
      run: mkdir production

    - name: Copy files to production
      run: |
        cp -r $(ls -A | grep -v production) production/

    - name: Show deployed files
      run: ls production

    - name: Rollback Completed
      run: echo "Rollback Successful!"