name: Rollback Deployment

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Enter tag to rollback'
        required: true

jobs:
  rollback:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Fetch Tags
      run: git fetch --all --tags

    - name: Checkout Tag
      run: git checkout tags/${{ github.event.inputs.tag }}

    - name: Redeploy
      run: |
        mkdir production
        cp -r * production/
        echo "Rollback Successful"