name: Rollback Deployment

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Enter tag to rollback'
        required: true

jobs:
  rollback:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0   # IMPORTANT: Fetch full history & tags

    - name: Checkout Selected Tag
      run: |
        git fetch --all --tags
        git checkout ${{ github.event.inputs.tag }}

    - name: Redeploy
      run: |
        mkdir -p production
        cp -r * production/
        echo "Rollback Successful!"